### ISSUE TITLE
Don't cache dev projects

### ISSUE THREAD

**Issue by chris-martin** [pex-tool/pex#159]
Every time I make a change to my code, I have to either upgrade the package version number or remove it from the pex cache to run the new code. So my build script looks like this:

```
rm ${PEX_HOME:-"$HOME/.pex"}/build/foo-*
pex --python python2.7 . --no-wheel
```

It would be nice if there were a way to specify that the dependency named `foo` should not be cached at all.

(Alternatively: The convention I'm used to on the JVM is to end a dev version number with `-snapshot`, and build tools know not to cache snapshot dependencies. But I don't know if python has a similar convention?)

Or am I using pex wrong?

**Comment by sixninetynine** [comment]
if you set `PEX_ALWAYS_CACHE=1` in your environment pex will always write a new cache when executing. This solves your dev use case, but bear in mind it's a global environment variable.

**Comment by StephanErb** [comment]
@chris-martin you could also try to solve this problem outside of `pex` by using `setuptools_scm` to generate your package version. It knows about your git and file changes and generates an auto-incremented version number.

**Comment by chris-martin** [comment]
@sixninetynine I just tried changing my command to

    env PEX_ALWAYS_CACHE=1 pex --python python2.7 . --no-wheel

and it's running an old cached version of the code, doesn't seem to help.

**Comment by jerluc** [comment]
@chris-martin Not sure if you're still having this issue, but I found one solution that works well at least if you are using [tox](https://tox.readthedocs.io/en/latest/). Ironically, I found the solution in pex's own [tox.ini file](https://github.com/pantsbuild/pex/blob/master/tox.ini#L11):

```
pex --cache-dir {envtmpdir}/buildcache wheel requests . -e pex.bin.pex:main --version
```

This basically works because tox knows to recreate the directory located at `{envtmpdir}`, which is effectively what you are doing with your `rm` command, but it's at least more integrated into an existing build workflow such as tox.

**Comment by kwlzn** [comment]
I think there are two factors here: build-time caching and run-time caching.

`--disable-cache` will turn off build-time caching, which has a similar effect as the tox.ini setting above except without the tmp dir creation. setting `PEX_ROOT` (the dir `pex` explodes run-time caches to) to a new temp dir on each run should solve the run-time caching problem in the no-version-bump case.

so probably something like this should work:

```
PEX_ROOT=$(mktemp -d) pex --disable-cache --python python2.7 .
```

and then you could most likely rely on your OS to cleanup the tmp dirs after the fact.

**Comment by kwlzn** [comment]
quick Slack copy/paste musing on a fix for the build-time caching:

```
> might be as easy as addressing the TODO here: https://github.com/pantsbuild/pex/blob/master/pex/resolvable.py#L115
> and then flipping https://github.com/pantsbuild/pex/blob/master/pex/resolvable.py#L250 to `exact/cacheable = False`
> so if your pattern is `pex .` it should use a `ResolvableDirectory` and not cache it
```

runtime caching is trickier - since the pex as-built is a finished product it's hard to conditionalize which deps to cache at runtime without specific configuration (e.g. a whitelist - maybe a hierarchical .pexrc config in the dev dir?). tho I think fully disabling runtime caching should be less costly, so the workarounds above are probably reasonable for that case?

**Comment by sitaktif** [comment]
Would it make sense to use checksums to invalidate the (build) cache when `pex` knows we're building from source?

**Comment by kwlzn** [comment]
for built-time caching, yeah invalidating all the time is ideal.

a possible solution to the runtime caching side of this tho might be to transitively fingerprint/checksum the local sources and then annotate any produced bdist (e.g. a whl) with the fingerprint as a PEP440 local version identifier, which would lead to optimal cache keying at runtime (due to the fingerprint being a first class member of the version). ..but it might be slightly tricky to implement the local version identifier injection without modifying `setup.py`?

also noting that this issue is unclaimed if anyone is game to contribute a PR.

**Comment by jsirois** [comment]
This has long since been fixed.
For example, given this small project:
```console
:; cat foo/data
1
:; cat foo/__main__.py
import pkgutil


if __name__ == "__main__":
    print(pkgutil.get_data(__name__, "data").decode("utf-8").strip())
:; cat setup.py
from setuptools import setup


setup(
    name="foo",
    version="0.1.0",
    packages=["foo"],
    include_package_data=True,
)
:; cat MANIFEST.in
include foo/data
```

Any edits made to the project are reflected in the PEX generated from the project:
```console
:; pex -mfoo . -opex1
:; echo 2 > foo/data
:; pex -mfoo . -opex2
:; echo 42 > foo/data
:; pex -mfoo . -opex42
:; ./pex1
1
:; ./pex2
2
:; ./pex42
42
```
