### ISSUE TITLE
`pex3 lock sync` isn't a no-op when it seems like it should be

### ISSUE THREAD

**Issue by benjyw** [pex-tool/pex#2519]
This is on MacOS on an M1:

```
$ rm -f lockfile.json
$ python -m pex.cli lock sync --style strict --interpreter-constraint $'CPython>=3.10,<3.11' --indent 2 --lock lockfile.json  'bloom-filter2>=2.0.0'
$ python -m pex.cli lock sync --style strict --interpreter-constraint $'CPython>=3.10,<3.11' --indent 2 --lock lockfile.json  'bloom-filter2>=2.0.0'
Updates for lock generated by cp310-cp310-macosx_14_0_arm64:
  Updated bloom-filter2 2 artifacts:
    + https://files.pythonhosted.org/packages/52/d7/871408c1c1230af64eb00e2064f6e8a065ae652f17f010b3f4f102e5fbac/bloom_filter2-2.0.0-py3-none-any.whl
    - https://files.pythonhosted.org/packages/2b/5d/8de4a849ebe212217e6d8f4798a6918d4035e741c44730da81272f170b47/bloom-filter2-2.0.0-1.tar.gz
$ python -m pex.cli lock sync --style strict --interpreter-constraint $'CPython>=3.10,<3.11' --indent 2 --lock lockfile.json  'bloom-filter2>=2.0.0'
No updates for lock generated by cp310-cp310-macosx_14_0_arm64.
$ python -m pex.cli lock sync --style strict --interpreter-constraint $'CPython>=3.10,<3.11' --indent 2 --lock lockfile.json  'bloom-filter2>=2.0.0'
No updates for lock generated by cp310-cp310-macosx_14_0_arm64.
$ 
```

The first invocation generates the lockfile. I would expect the second to be a no-op, since no inputs have changed (and neither has the state on PyPI). Yet it updates the artifact, as logged. The diff between the two lockfile versions confirms this:

```
15,16c15,16
<               "hash": "310e5d3aa15be6e3d2285a7111f60cc44a1f500159412f2c72d155f43037cefd",
<               "url": "https://files.pythonhosted.org/packages/2b/5d/8de4a849ebe212217e6d8f4798a6918d4035e741c44730da81272f170b47/bloom-filter2-2.0.0-1.tar.gz"
---
>               "hash": "f9d3a3a44ae917ab9c13f71b542ac88b863f0cf4e64afbca48777cf0d5310c93",
>               "url": "https://files.pythonhosted.org/packages/52/d7/871408c1c1230af64eb00e2064f6e8a065ae652f17f010b3f4f102e5fbac/bloom_filter2-2.0.0-py3-none-any.whl"
```

I'll note that this is one of possibly a couple of odd phenomena I noticed while testing `lock sync` on a large set of input requirements, but this was the easiest one to isolate in a small example. I will look further into this and the others, but wanted to file this to record my findings.

**Comment by jsirois** [comment]
Although all examples are very welcome - Pex needs to handle this - I would be very interested to know if you get this sort of thing with _anything_ else because `bloom-filter2-2.0.0-1.tar.gz` is not a valid artifact name for `bloom-filter2 2.0.0`, unlike `bloom_filter2-2.0.0-py3-none-any.whl` which is valid. I will note also that you're suspiciously not using `--pip-version`; so if you're on Python 3.11 or less, you're getting 20.3.4 by default.

**Comment by jsirois** [comment]
Ok, yeah - this reproduces all the way up until Pip 23.2, at which point you get a very unfriendly hard error:
```console
:; python -m pex.cli lock sync --style strict --interpreter-constraint "CPython>=3.10,<3.11" --indent 2 --lock lockfile.json  "bloom-filter2>=2.0.0" --pip-version 23.2
Pin(project_name=ProjectName(raw='bloom_filter2', validated=False, normalized='bloom-filter2'), version=Version(raw='2.0.0', normalized='2'))

:; python -m pex.cli lock sync --style strict --interpreter-constraint "CPython>=3.10,<3.11" --indent 2 --lock lockfile.json  "bloom-filter2>=2.0.0" --pip-version 23.2 -v
pex: Hashing pex: 18.5ms
pex: Isolating pex: 0.1ms
pex: Resolving for:
pex: Resolving for:inux_2_39_x86_64 interpreter at /home/jsirois/.pyenv/versions/3.10.14/bin/python3.10
  cp310-cp310-manylinux_2_39_x86_64 interpreter at /home/jsirois/.pyenv/versions/3.10.14/bin/python3.10: 923.7ms
pex: Creating lock from resolve: 13.0ms
pex:   Building 0 source distributions to gather metadata for lock.: 8.6ms
pex: Indexing downloads: 0.3ms
Traceback (most recent call last):
  File "/home/jsirois/dev/pex-tool/pex/pex/result.py", line 105, in catch
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/dev/pex-tool/pex/pex/cli/command.py", line 110, in run
    return subcommand_func(self)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/dev/pex-tool/pex/pex/cli/commands/lock.py", line 1567, in _sync
    create(
  File "/home/jsirois/dev/pex-tool/pex/pex/resolve/lockfile/create.py", line 438, in create
    create_lock_download_manager = CreateLockDownloadManager.create(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jsirois/dev/pex-tool/pex/pex/resolve/lockfile/create.py", line 100, in create
    artifact_and_project_name = source_artifacts_by_pin[pin]
                                ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: Pin(project_name=ProjectName(raw='bloom_filter2', validated=False, normalized='bloom-filter2'), version=Version(raw='2.0.0', normalized='2'))
Pin(project_name=ProjectName(raw='bloom_filter2', validated=False, normalized='bloom-filter2'), version=Version(raw='2.0.0', normalized='2'))
```

**Comment by jsirois** [comment]
Yeah, starting with Pip 23.2 it notices the borked sdist and moves to the wheel:
```console
...
2024-09-06T20:05:22,231   Source in /home/jsirois/.cache/pex/pip/0/23.2/pip_cache/.tmp/pip-download-t7vs17db/bloom-filter2_4ecd4f11fc2a46299fc289bba06838e8 has version 2.0.0, which satisfies requirement bloom-filter2>=2.0.0 from https://files.pythonhosted.org/packages/2b/5d/8de4a849ebe212217e6d8f4798a6918d4035e741c44730da81272f170b47/bloom-filter2-2.0.0-1.tar.gz
2024-09-06T20:05:22,231   Removed bloom-filter2>=2.0.0 from https://files.pythonhosted.org/packages/2b/5d/8de4a849ebe212217e6d8f4798a6918d4035e741c44730da81272f170b47/bloom-filter2-2.0.0-1.tar.gz from build tracker '/home/jsirois/.cache/pex/pip/0/23.2/pip_cache/.tmp/pip-build-tracker-hecovgk4'
2024-09-06T20:05:22,231 Discarding [blue underline]https://files.pythonhosted.org/packages/2b/5d/8de4a849ebe212217e6d8f4798a6918d4035e741c44730da81272f170b47/bloom-filter2-2.0.0-1.tar.gz (from https://pypi.org/simple/bloom-filter2/)[/]: [yellow]Requested bloom-filter2>=2.0.0 from https://files.pythonhosted.org/packages/2b/5d/8de4a849ebe212217e6d8f4798a6918d4035e741c44730da81272f170b47/bloom-filter2-2.0.0-1.tar.gz has inconsistent version: expected '2.0.0.post1', but metadata has '2.0.0'[reset]
2024-09-06T20:05:22,232   Obtaining dependency information for bloom-filter2>=2.0.0 from https://files.pythonhosted.org/packages/52/d7/871408c1c1230af64eb00e2064f6e8a065ae652f17f010b3f4f102e5fbac/bloom_filter2-2.0.0-py3-none-any.whl.metadata
2024-09-06T20:05:22,232   Created temporary directory: /home/jsirois/.cache/pex/pip/0/23.2/pip_cache/.tmp/pip-unpack-11uh0da2
2024-09-06T20:05:22,233   Looking up "https://files.pythonhosted.org/packages/52/d7/871408c1c1230af64eb00e2064f6e8a065ae652f17f010b3f4f102e5fbac/bloom_filter2-2.0.0-py3-none-any.whl.metadata" in the cache
...
```

The bug in that case is Pex's log scraping sees the initial success-looking lines for the sdist and captures that as the artifact. So that needs to be fixed for modern Pip scraping.

**Comment by jsirois** [comment]
I think in the legacy case Pex internals must be fooled by the 2.0.0-1 mismatch with the 2.0.0 version triggering a non-noop-sync for the 2nd run ... I'll have to dig a bit deeper there.

**Comment by benjyw** [comment]
> Although all examples are very welcome - Pex needs to handle this - I would be very interested to know if you get this sort of thing with _anything_ else because `bloom-filter2-2.0.0-1.tar.gz` is not a valid artifact name for `bloom-filter2 2.0.0`, unlike `bloom_filter2-2.0.0-py3-none-any.whl` which is valid. I will note also that you're suspiciously not using `--pip-version`; so if you're on Python 3.11 or less, you're getting 20.3.4 by default.

I'll follow up as I track down the other issues I was seeing (or assign them to my own errors or misunderstandings), but I tend to think they are unrelated to this one, which does indeed seem like quite an edge case. 

I wasn't using `--pip-version` because, when I did force modern pip, the original (large) resolve didn't finish in many minutes, whereas it took around 50 seconds with legacy pip. So evidently some other weird (pip, not pex) edge case there, which I will dig into as well.

**Comment by jsirois** [comment]
Ok, I can concoct no way to fix the 2nd and further runs for old Pip detecting this change:
```
Updates for lock generated by cp310-cp310-macosx_14_0_arm64:
  Updated bloom-filter2 2 artifacts:
    + https://files.pythonhosted.org/packages/52/d7/871408c1c1230af64eb00e2064f6e8a065ae652f17f010b3f4f102e5fbac/bloom_filter2-2.0.0-py3-none-any.whl
    - https://files.pythonhosted.org/packages/2b/5d/8de4a849ebe212217e6d8f4798a6918d4035e741c44730da81272f170b47/bloom-filter2-2.0.0-1.tar.gz
```

The root issue is the sdist artifact name not matching its metadata version as mentioned above.
Resolution for the initial lock creation proceeds as follows for the sole relevant criteria of `bloom-filter2>=2.0.0`:

Pip<23.2:
1. Find bloom-filter2-2.0.0-1.tar.gz and bloom_filter2-2.0.0-py3-none-any.whl
2. Pick bloom-filter2-2.0.0-1.tar.gz which translates as 2.0.0.post1 and is the newest version
   satisfying the requirement.
4. Gather bloom-filter2-2.0.0-1.tar.gz metadata and succeed.

Pip>=23.2:
1. Find bloom-filter2-2.0.0-1.tar.gz and bloom_filter2-2.0.0-py3-none-any.whl
2. Pick bloom-filter2-2.0.0-1.tar.gz which translates as 2.0.0.post1 and is the newest version.
3. Gather bloom-filter2-2.0.0-1.tar.gz metadata fail due to version mismatch.
5. Backtrack to older version wheel and pick bloom_filter2-2.0.0-py3-none-any.whl

So, in the initial lock sync, old Pip picks the sdist and new Pip picks the wheel. For the new Pip case, Pex gets confused and dies. I have a fix for that and subsequent syncs using new Pip continue to find no changes.

For old Pip on subsequent syncs, resolution now must satisfy two criteria:
+ original unchanged requirement: `bloom-filter2>=2.0.0`
+ constraint to pin no movement for unchanged top-level requirements: `bloom-filter2==2.0.0`
Resolution then proceeds as follows:
1. Find only bloom_filter2-2.0.0-py3-none-any.whl satisfying the new, tighter criteria. [^1]

So I'll post a PR here shortly that fixes this for Pip>=23.2, but there just is no fix for older Pips when a project's latest release includes mixed-version artifacts in this way. This should be a decidedly small corner case that can either be worked around by using a modern `--pip-version` or else specifying `--prefer-binary`.

[^1]: 2.0.0.post1 != 2.0.0 as spelled out here: https://packaging.python.org/en/latest/specifications/version-specifiers/#version-matching

**Comment by jsirois** [comment]
I just noticed an odd thing about your setup @benjyw that is not related to this issue, but that you should be aware of. The phrase `--style strict --interpreter-constraint 'CPython>=3.10,<3.11'` tells `pex3 lock ...` to:
1. Find all interpreters on the local machine that match the constraint `CPython>=3.10,<3.11`.
2. For each target (interpreter) found in 1., generate a strict lock.

The same goes for `--style sources` save for the fact that an sdist is always collected if present in addition to any matching wheel.

It is only for `--style universal` that Pip patching is done to consider the whole range of 'CPython>=3.10,<3.11'. The danger here is 'CPython>=3.10,<3.11' - or, equivalently, 'CPython==3.10.*' - looks like it means 1 interpreter, but it really means any one of 16 (currently) interpreters by patch version and even more when you consider, for example, glibc versions on Linux.

So, if your machine only has CPython 3.10.15 that meets 'CPython>=3.10,<3.11', that single interpreter will be used to generate 1 strict locked resolve in the lock file. That will select a project that has an environment marker of `; python_full_version >= '3.10.1'`, for example. In other words, that lock will _not_ work for CPython 3.10.0 which _is_ in the IC range, and that likely surprises you!

The moral of the story is strict means what it says and locks for exactly 1 interpreter. Its strict. What you see is what you get. If you lock and test with that interpreter, that interpreter is known to work with the lock definitively. The single target may be a local interpreter or a remote interpreter (`--complete-platform`), or a remote ill-specified interpreter (`--platform`), but the locked resolve is intended to work exactly for the selected targets and only the selected targets. Of all the target selection methods (`--python`, --complete-platform`, `--platform`, `--interpreter-constraint`), its only `--interpreter-constraint` that selects multiple local targets and can do so with "holes". This is the same situation as when building PEX files instead of creating locks. If you build an `--interpreter-constraint 'CPython>=3.8,<3.13'` PEX but your machine only has CPython 3.10.15, then the PEX is only guaranteed to work with CPython 3.10.15. If there are C extensions, the PEX will fail for 3.8, 3.9, 3.11, and 3.12 not to mention the strange `; python_full_version >= '3.10.1'` corner cases which do exist in the wild.

**Comment by jsirois** [comment]
> the original (large) resolve didn't finish in many minutes, whereas it took around 50 seconds with legacy pip. So evidently some other weird (pip, not pex) edge case there

@benjyw I think you know (or knew) this, but in case not, the vendored Pip up until 23.2 all support and default to `--resolver-version pip-legacy-resolver`. That resolver does 0 backtracking so it both will always be faster than any modern Pip resolver, but at the cost of being buggy. So it's not really interesting to use the legacy resolver or compare to it. More interesting is speed improvements or regressions holding `--resolver-version pip-2020-resolver` constant.

**Comment by benjyw** [comment]
Yes, I did know that those all default to the legacy resolver. But I did not actually know that legacy resolver would always be faster (just that it would sometimes be less correct, up to failing to resolve when a solution should exist). I thought it did attempt some sort of bad backtracking. But either way, yeah, the legacy resolver is not of abiding interest.

**Comment by benjyw** [comment]
> Ok, I can concoct no way to fix the 2nd and further runs for old Pip detecting this change:
> 

Thanks for the clear explanation of this. Obviously it should never have been possible to publish artifacts with broken names, but that's how the ecosystem is I guess...

**Comment by benjyw** [comment]
> I just noticed an odd thing about your setup @benjyw that is not related to this issue, but that you should be aware of. The phrase `--style strict --interpreter-constraint 'CPython>=3.10,<3.11'` tells `pex3 lock ...` to:
> 

Thanks very much for this explanation, which my previous understanding did not match, so this is very valuable and I will figure out what it means for the project I'm working on (which I will tell you about separately if of interest).

**Comment by benjyw** [comment]
PS we can close this with https://github.com/pex-tool/pex/pull/2524, I will open new tickets if I discover other issues, this one really is specific.
