### ISSUE TITLE
provide a helper library to extract files/resources from pex files

### ISSUE THREAD

**Issue by kwlzn** [pex-tool/pex#299]
depending on whether or not a pex is zip_safe=False, accessing resources for something as simple as Flask template access can take two wildly varying code paths.

it'd be great if pex could provide a utility library for resource extraction that would simplify this for end users and provide uniform access and reference to resources in a pex - regardless of how the pex itself is configured.

we could then recommend this in lieu of `pkg_resources.resource_*` for more user friendly resource extraction.

**Comment by JieGhost** [comment]
Is it like a tarfile module for pex files?

**Comment by jsirois** [comment]
Pex has long since changed its runtime execution to always execute in an unpacked form, whether running in traditional PEX zipapp mode or `--venv` mode. In either case, use code is always unpacked on disk; so it can uniformly access resources using `__file__` if it wishes. The `zip_safe` option is now documented as vestigal / no-op:
```
:; pex -h | grep -A3 zip-safe
  --zip-safe, --not-zip-safe
                        Deprecated: This option is no longer used since user
                        code is now always unzipped before execution.
                        (default: None)
```

As such, I believe there is no longer a need for such a helper.
