### ISSUE TITLE
Dependencies distributed as namespace packages give import errors

### ISSUE THREAD

**Issue by zaininfo** [pex-tool/pex#331]
I am trying to build a PEX file using Python 3.5 for a project which has [google-cloud-storage](https://pypi.python.org/pypi/google-cloud-storage) as one of its dependencies.
The PEX file is created fine, but an import error is thrown when I try to run the entry point script.
```sh
ImportError: No module named 'google.cloud'
```
I was getting the same error with Pylint, and resolved it by suppressing the error or importing the module dynamically.
The dependency in question is distributed as a namespace package (using Setuptools convention), which has known issues with Pylint.

Project hierarchy:
```
- google
    __init__.py
    - cloud
        __init__.py
        - storage
            __init__.py
            ...
```
Namespace `__init__.py` files:
```py
# ...

try:
    import pkg_resources
    pkg_resources.declare_namespace(__name__)
except ImportError:
    import pkgutil
    __path__ = pkgutil.extend_path(__path__, __name__)
```
Does PEX support such packages as dependencies of a project?

**Comment by kwlzn** [comment]
unfortunately, not currently - tho I think we should probably implement this support. a PR would be welcome if you're interested in contributing.

**Comment by zaininfo** [comment]
Thanks for the clarification (updated my initial comment to add some context).
I'll be more than happy to contribute, if I manage to put together a decent solution.

**Comment by lmctv** [comment]
For what it's worth, I just stumbled in the same problems while trying to build a pex file out of azure-cli package, both using a python3.5 and a python2.7, with a minimal requirements.txt file containings just the
```
azure-cli
```
line, the pexfile seems to build fine, with
```
py-{27,35}-pex-venv/bin/pex -o az.pex  -r requirements.txt --pre --wheel --build -m azure.cli
```
but when trying to execute the resulting pex file, both the python2.7 and python3.5 versions fail, with the former always raising an
```
ImportError: No module named azure.cli.core.decorators
```
exception from the `import azure.cli.core.decorators` line in `azure_cli_core/azure/cli/core/telemetry_upload.py`
and printing the
```
ERROR: Error loading command module 'batch'
ERROR: Error loading command module 'storage'
```
on standard error;
and the latter changing behaviour from the first time it's invoked, when it raises the same exception as python2.7, to the later ones, when it raises an
```
ImportError: No module named azure.cli.__main__; 
        'azure.cli' is a package and cannot be directly executed
```

**Comment by rmihael** [comment]
I also got hit by this problem today. Azure dependency got packaged but fails during runtime. Is there any workaround for it? It's a blocker that prevents us from adopting PEX.

**Comment by jjmurre** [comment]
Got bitten by the same issue. Seems that namespaced dependencies are silently ignored and do not end up in the pex file. Althought I really like pex, this is a real showstopper for me.

**Comment by bjorn-spire** [comment]
I've also been stuck on trying to use `google.cloud` for one of my apps that's managed through Pants/Pex. But I figured out, but I don't remember how, that if I copied the `.dist-info` folders for all packages that contained a `namespace_packages.txt` file into the root folder of the `.pex` then it would work. 

So I have a little shell script that unzips the pex, finds all the packages with a namespace_packages.txt, copies, rezips and then take it from there.

In case that can help anyone else out. :)

**Comment by warsaw** [comment]
We're seeing very similar errors with our internal applications built with pex 1.2.13.  The failures are indeterminate though; we have a script that attempts the namespace package import on an unpacked pex directory.  It fails roughly every 30 times.  The only thing that I can think of that's different between the script invocations is the Python process (we're using 3.6), and the only thing that I can think of that's related to this is hash randomization.  On a hunch, we ran the same script with `PYTHONHASHSEED=0` and have yet to see a failure after hundreds of runs of the script.  That somewhat jives with my intuition that it's a `.pth` processing order problem.  I.e. if there's a bad `.pth` file somewhere (or maybe not even bad, but just with an implicit order dependency), and we get unlucky so that pex processes the `.pth` files in the wrong order, the namespace packages can't get imported.  It's a little odd because in 3.6, dictionary iteration order preserves insertion order, so it's not a complete explanation.  There's also a weirdness that if we take a pex built on a local machine rather than our build host, the script never fails.  But maybe the `PYTHONHASHSEED` data point is enough of a clue to help nail down the problem.

**Comment by warsaw** [comment]
We have a working theory, although we haven't run it to ground.  Despite the use of `OrderedSet` in pex, there are some order indeterminate operations.  Specifically, I think the order in which dists are activated is dependent on `PYTHONHASHSEED`.  Couple that with a broken `.pth` file, and if you're unlucky enough to load that broken `.pth` file early, the exception gets swallowed *and* pex stops loading subsequent `.pth` files, thus breaking the later namespace packages.  If you're lucky enough to load the broken `.pth` file later, you can get mostly working namespace packages (although, anything after the broken `.pth` file will not be importable).

Once you find the `PYTHONHASHSEED` value that causes the unfortunate ordering, the problem is 100% reproducible.  I got lucky; my loop searching for `PYTHONHASHSEED` found the failure at 119.  Of course, this was *exceedingly* lucky given how big that environment variable can be.

So I think the ask for pex is twofold:

* Provide much better diagnostics when broken `.pth` files are loaded
* When a broken `.pth` file is loaded, *either* skip it and continue or fail fatally

It seems like the current behavior is the worst of both worlds: the exception in the `.pth` file is swallowed *and* pex stops processing further `.pth` files.

(The fact that we have a broken `.pth` file is of course our problem, but we need better diagnostics and behavior from pex to be able to find that brokenness.)

**Comment by bjorn-spire** [comment]
One of my colleagues figured out if you empty the module list and try to import the package again it'll work. So we came up with this hack that has helped us work around it:

```python
# This seems to be sufficient to fix my import problems.
# If this happens to work outside of this project, we'll move it to commons
import sys

for _ in range(5):
    try:
        import google
        import google.cloud
        import google.cloud.bigquery
        break
    except (ModuleNotFoundError, ImportError):
        print('BQ Import hack triggered! retrying')
        for module in list(sys.modules):
            if module.startswith('google'):
                del sys.modules[module]
else:
    raise ImportError('BQ Import hack failed')

# If we reach this, the hack must've worked.
from google.cloud import bigquery
```

So wherever we need the bigquery library we do `from spire.commons.bigquery.import_hack import bigquery`

**Comment by bjorn-spire** [comment]
@kwlzn do you, or anyone else, have a feeling where to start to have a stab at fixing this? :)

I'm keen to at least give it a go but I'm not sure where to start…

**Comment by georgi-yanchev** [comment]
Looks like packages are activated in a random order (The order in which a `set` is iterated). `pkg_resources` package will build its `working_set` upon the first import, and it happens to be when the first namespace package is activated.

I've posted: https://github.com/pantsbuild/pex/pull/713 to delay that import until `sys.path` is fully prepared.

**Comment by jsirois** [comment]
@zaininfo et. al.: This has long since been fixed. I'm just seeing this now and circling back.

For example, Pex not only handles `pkg_resources` style namespace packages, but it bends over backwards to do so:
```console
# Using the google-cloud-storage distribution released at the time of the OP:
:; pex google-cloud-storage==0.21.0 -o google-cloud-storage-0.21.0.pex

:; ./google-cloud-storage-0.21.0.pex
/home/jsirois/.pex/unzipped_pexes/9f49ba21596bbedd580f0b208fc8575c5e1865aa/.bootstrap/pex/environment.py:771: PEXWarning: The `pkg_resources` package was loaded from a pex vendored version when declaring namespace packages defined by:

1. google-cloud-storage==0.21.0 namespace packages:
  google
  google.cloud

These distributions should fix their `install_requires` to include `setuptools`
  pex_warnings.warn(
Pex 2.16.1 hermetic environment with 1 requirement and 16 activated distributions.
Python 3.11.9 (main, Apr 26 2024, 19:20:24) [GCC 13.2.0] on linux
Type "help", "pex", "copyright", "credits" or "license" for more information.
>>> import google
>>> import google.cloud
/home/jsirois/.pex/installed_wheels/cf452147b39cecf9e57c154b520a2328971d65996cad9a633a3db5afdad5b0ca/google_cloud_storage-0.21.0-py2.py3-none-any.whl/google
/home/jsirois/.pex/installed_wheels/a9e6a4422b9ac5c29f79a0ede9485473338e2ce78d91f2370c01e730eab22e61/google_cloud_core-2.4.1-py2.py3-none-any.whl/google
/home/jsirois/.pex/installed_wheels/f12a9b8309b5e21d92483bbd47ce2c445861ec7d269ef6784ecc0ea8c1fa6125/google_api_core-2.19.1-py3-none-any.whl/google
/home/jsirois/.pex/installed_wheels/27a2499c7e8aff199665b22741997e485eccc8645aa9176c7c988e6fae507945/googleapis_common_protos-1.63.2-py2.py3-none-any.whl/google
/home/jsirois/.pex/installed_wheels/a55c48f2a2092d8e213bd143474df33a6ae751b781dd1d1f4d953c128a415b25/protobuf-5.27.3-cp38-abi3-manylinux2014_x86_64.whl/google
/home/jsirois/.pex/installed_wheels/8eff47d0d4a34ab6265c50a106a3362de6a9975bb08998700e389f857e4d39df/google_auth-2.33.0-py2.py3-none-any.whl/google
>>> print("\n".join(google.cloud.__path__))
/home/jsirois/.pex/installed_wheels/cf452147b39cecf9e57c154b520a2328971d65996cad9a633a3db5afdad5b0ca/google_cloud_storage-0.21.0-py2.py3-none-any.whl/google/cloud
/home/jsirois/.pex/installed_wheels/a9e6a4422b9ac5c29f79a0ede9485473338e2ce78d91f2370c01e730eab22e61/google_cloud_core-2.4.1-py2.py3-none-any.whl/google/cloud
/home/jsirois/.pex/installed_wheels/27a2499c7e8aff199665b22741997e485eccc8645aa9176c7c988e6fae507945/googleapis_common_protos-1.63.2-py2.py3-none-any.whl/google/cloud
>>>
```
Note the warning above:
```
PEXWarning: The `pkg_resources` package was loaded from a pex vendored version when declaring namespace packages defined by:

1. google-cloud-storage==0.21.0 namespace packages:
  google
  google.cloud
```

Moving on to 0.22.0, which has fixed this `setuptools` undeclared dep as well as an `httplib2` undeclared dep:
```
:; pex google-cloud-storage==0.22.0 -o google-cloud-storage-0.22.0.pex

:; ./google-cloud-storage-0.22.0.pex
Pex 2.16.1 hermetic environment with 1 requirement and 14 activated distributions.
Python 3.11.9 (main, Apr 26 2024, 19:20:24) [GCC 13.2.0] on linux
Type "help", "pex", "copyright", "credits" or "license" for more information.
>>> import google
>>> import google.cloud
>>> from google.cloud import storage
>>> print("\n".join(google.__path__))
/home/jsirois/.pex/installed_wheels/490451279bb03966b002f2b836abadb3943dd907a55c8d34b5f187277f117257/google_cloud_storage-0.22.0-py2.py3-none-any.whl/google
/home/jsirois/.pex/installed_wheels/df28b42006be41e60a8d826759681e4b36b4c23c1f62b325191707a116eff04b/google_cloud_core-0.22.1-py2.py3-none-any.whl/google
/home/jsirois/.pex/installed_wheels/997516b42ecb5b63e8d80f5632c1a61dddf41d2a4c2748057837e06e00014258/google_auth-1.35.0-py2.py3-none-any.whl/google
/home/jsirois/.pex/installed_wheels/27a2499c7e8aff199665b22741997e485eccc8645aa9176c7c988e6fae507945/googleapis_common_protos-1.63.2-py2.py3-none-any.whl/google
/home/jsirois/.pex/installed_wheels/a55c48f2a2092d8e213bd143474df33a6ae751b781dd1d1f4d953c128a415b25/protobuf-5.27.3-cp38-abi3-manylinux2014_x86_64.whl/google
>>> print("\n".join(google.cloud.__path__))
/home/jsirois/.pex/installed_wheels/490451279bb03966b002f2b836abadb3943dd907a55c8d34b5f187277f117257/google_cloud_storage-0.22.0-py2.py3-none-any.whl/google/cloud
/home/jsirois/.pex/installed_wheels/df28b42006be41e60a8d826759681e4b36b4c23c1f62b325191707a116eff04b/google_cloud_core-0.22.1-py2.py3-none-any.whl/google/cloud
/home/jsirois/.pex/installed_wheels/27a2499c7e8aff199665b22741997e485eccc8645aa9176c7c988e6fae507945/googleapis_common_protos-1.63.2-py2.py3-none-any.whl/google/cloud
>>> print(storage.__file__)
/home/jsirois/.pex/installed_wheels/490451279bb03966b002f2b836abadb3943dd907a55c8d34b5f187277f117257/google_cloud_storage-0.22.0-py2.py3-none-any.whl/google/cloud/storage/__init__.py
>>>
```
