### ISSUE TITLE
ZIP64 extension for PEX

### ISSUE THREAD

**Issue by leozc** [pex-tool/pex#422]
We have a PEX need to include a bunch of files - and the number of files is exceeded 64K (typical ZIP limit)

I saw this error message: “Exception message: Files count would require ZIP64 extensions”

Is it possible to get PEX use ZIP64 extension?

**Comment by leozc** [comment]
Try to build a Zip has large than 65K files - you would see this error

**Comment by nimish** [comment]
IIRC zip64 is not supported as a format for python to load modules from directly so that feature would likely break

**Comment by leozc** [comment]
@nimish thanks for the context ...

**Comment by nimish** [comment]
In terms of actually getting ZIP64 enabled, someone would have to pass `allowZip64=True` into the zip creator while also ensuring that the pex is unzipped before loading.

**Comment by jsirois** [comment]
Pex does use ZIP64 extensions when it interacts with zip files since #1926. That said @leozc, the problem you describe happens before the PEX file is running. In order for the PEX file to even boot, the Python interpreter launching it must be able to use its zipimporter against a zip with ZIP64 extensions. This was not supported until the CPython 3.13 series (see here: https://docs.python.org/3.13/whatsnew/3.13.html#zipimport).

Pex did add support for `--layout {loose,packed,zipapp}` though in #1438. Many folks use `--layout packed` to work around this issue with older Python not being able to zipimport a ZIP64 zip.

I'm going to close this as an answered question, but speak up if you have more questions about all this.
