### ISSUE TITLE
add a PEX-INFO metadata versioning scheme

### ISSUE THREAD

**Issue by wickman** [pex-tool/pex#69]
We should add a metadata versioning so that we can at least know whether we expect to be able to read/parse metadata from a certain generation.

**Comment by jsirois** [comment]
Since the 2.x release, Pex has followed strict backwards compatibility as a whole. In particular, PEX-INFO evolution has occurred and accommodated missing fields and even fields that have changed content. For example `inherit_path` used to be a bool and now is a string enum:
https://github.com/pex-tool/pex/blob/af748148f9e8d7c0600939a2cbb664a14ba5966d/pex/inherit_path.py#L22-L35
