### ISSUE TITLE
Enhance cache validation/purging when caching wheels

### ISSUE THREAD

**Issue by CMLivingston** [pex-tool/pex#706]
## Problem

In Twitter's CI pipeline, we are seeing assertion errors from the last line of https://github.com/pantsbuild/pex/blob/master/pex/util.py#L168. This comes from a pex tool that use wrapper C code to set-uid to a temporary user with unique permissions to other systems, and as a result, a PEX_ROOT needs to be somewhere shared. The author of this tool elected to put it in `/tmp/<tool>`. Upon inspection of the cache that fails to load a dist, it appears that the cache at PEX_ROOT is properly formatted dir path-wise, but does not contain any `pyc` files or sources in each wheel directory, indicating a bad write.

The root cause of this issue is still under investigation and has proven difficult to reliably reproduce, but we suspect it is likely a disk race - either due to PEX_ROOT being set to a subdir of /tmp or multiple tenants using PEX_ROOT (via `cache_distribution`) at the same time (less likely). There is also a question of whether the set-uid gymnastics are causing misaligned permissions at read vs. write times.

### Proposal

Aside from us figuring out why the cache got into this state, this is an opportunity to enhance  cache read robustness for the cases where a cache appears normal but has been corrupted somehow. Currently, the logic of `cache_distribution` checks if the cached wheel dirs exist, and not if they are well formed. It would be useful to add a fix that checked if we could load the distribution from cache, and blew it away and re-cached on failure. Some sort of mutex or lock file might even make sense depending on whether this is indeed the result of a disk race, but the root cause is still unknown.

**Comment by CMLivingston** [comment]
ping @jsirois for thoughts on this.

**Comment by jsirois** [comment]
> and as a result, a PEX_ROOT needs to be somewhere shared

Why? Can't PEX_ROOT be an ephemeral tmp dir instead of fixed one? PEX_ROOT is just involved in optimizations, nothing more. Is speed of pex startup in this case critical / limiting?

As far as thoughts go, I would rather, in order:
1. Hear the real issue you continue to dig into and find a full explanation for.
2. Fix cache writing - perhaps inspect 1st, but pex simply should not be able to write a bad cache entry.
3. Go down the road you propose.

I fear the real issue in 1 combining with 3 to get us a nice endless loop.
