### ISSUE TITLE
Support for pex in zip hostile environments.

### ISSUE THREAD

**Issue by hrfuller** [pex-tool/pex#912]
There are certain environments where it would be useful to use pex to bundle applications, but which need the entrypoint of pex to be the real `__main__` module. For instance if an application running in a pex wants to pickle itself, to support remotely executing code in the pex, an application that is gaining popularity due to ubiquity of  cloud environments, and libraries that try to seamlessly link local and remote execution. @jsirois suggested calling these types of applications `zip hostile`.

A possible solution to this incompatibility would be to add a new execution time flag (and environment variable) to make pex completely unzip itself, including pex bootstrapping code, and have the pex bootstrapper re-exec itself as a python process using the module specified as the entrypoint as the main module. This style of pex execution would be essentially identical to running source files locally, and therefore should perform like non-pex'ed applications.

**Comment by jsirois** [comment]
This has since been implemented. A traditional PEX now always unzips itself to the `PEX_ROOT` and re-execs. It re-execs the unzipped PEX `__main__.py` though and not the user module directly (after all, `-m <module>` is just one possible entry point style, `-e <module>:<function>` is another. Likewise, a `--venv` mode PEX installs itself as a traditional venv under the `PEX_ROOT` and re-executes a bare `__main__.py` file in the root of the venv. I think this is all that is required for pickling to work (plus the fix in #1018).
